from app.models import Alert


EXPLANATION_TEMPLATES = {
    "port_scan": {
        "summary": "A single source contacted many destination ports in a short time window.",
        "pattern": (
            "This pattern is commonly associated with port scanning, where a host probes multiple ports "
            "to discover exposed services before a possible follow-up attempt."
        ),
        "recommended_action": (
            "Review the source host, check whether the activity was expected scanning, and restrict or "
            "firewall unnecessary exposed services."
        ),
    },
    "dns_spike": {
        "summary": "This alert suggests an unusual burst of DNS activity from one source.",
        "pattern": "DNS spikes can indicate misconfiguration, malware lookup behavior, or discovery activity.",
        "recommended_action": "Review DNS queries from the source host and check for unexpected domains.",
    },
    "suspicious_port": {
        "summary": "This alert shows traffic to a sensitive service port.",
        "pattern": "Administrative or legacy service ports are common targets for probing and brute-force attempts.",
        "recommended_action": "Confirm the connection is expected and limit access to trusted hosts.",
    },
    "large_packet": {
        "summary": "This alert shows packet metadata above the large-packet threshold.",
        "pattern": "Very large packets can be normal in some environments, but may deserve review when unexpected.",
        "recommended_action": "Check whether the source and destination normally exchange high-volume traffic.",
    },
    "unknown_protocol": {
        "summary": "This alert shows a protocol outside the expected TCP, UDP, and ICMP set.",
        "pattern": "Unexpected protocol values may indicate unusual tooling, malformed metadata, or unsupported traffic.",
        "recommended_action": "Verify the collector output and inspect the source host if the protocol is unexpected.",
    },
}

FALLBACK_EXPLANATION = {
    "summary": "This alert was generated by a detection rule that matched suspicious network metadata.",
    "pattern": "The event pattern differed from expected baseline traffic.",
    "recommended_action": "Review the alert context and compare it with known activity for the source host.",
}


def select_explanation_template(rule_name: str) -> dict[str, str]:
    return EXPLANATION_TEMPLATES.get(rule_name, FALLBACK_EXPLANATION)


def explain_alert(alert: Alert) -> dict[str, str]:
    template = select_explanation_template(alert.rule_name)
    return {
        "alert_id": alert.id,
        "rule_name": alert.rule_name,
        **template,
    }
