name: Docker Build

on:
  push:
  pull_request:

jobs:
  docker:
    name: Docker compose build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build compose stack
        run: docker compose build
